<?php
/** @var \AHT\AttributeCustomer\Block\Template $block */
$helper = $this->helper('\AHT\AttributeCustomer\Helper\Data');
$allPhone = $helper->getAllPhoneCode();
?>
<fieldset>
    <legend>Organization Information</legend>
    <div class="field">
        <label for="country-code" class="label">Country</label>
        <div class="control">
            <select name="country-code" id="country-code">
                <?php
                    foreach($allPhone as $key => $value):
                    ?>
                <option value = "<?= $value?>"><?= $block->getCountryName($key) . " (+" . $value . ")" ?></option>
                <?php
                    endforeach;
                ?>
            </select>
        </div>
    </div>
    <div class="field contact_phone_number required">
        <label for="contact_phone_number" class="label">Contact phone number</label>
        <div class="control">
            <input type="text" id="contact_phone_number" name="contact_phone_number_show"/>
            <input type="hidden" id="contact_phone_number_hidden" name="contact_phone_number"/>
        </div>
    </div>

    <div class="field company_type required">
        <label for="company_type" class="label">Company type</label>
        <div class="control">
            <select id="company_type" name="company_type">
                <option value="" disabled>Please select</option>
                <option value="1">CBD Manufacturer</option>
                <option value="2">CBD Brand and Marketing company</option>
                <option value="3">CBD Extractor</option>
                <option value="4">Other</option></option>
            </select>
        </div>
    </div>

    <div class="field organization_name" id="field-other">
        <label for="organization_name" class="label">Organization name</label>
        <div class="control" >
            <input type="text" id="organization_name" name="organization_name"/>
        </div>
    </div>
</fieldset>
<script>
require(['jquery'], function ($){
    $(document).ready(function(){
        $('#field-other').hide();

        $('#contact_phone_number').change(function (){
            var code = $('#country-code').val();
            var phone = $(this).val();
            $('#contact_phone_number_hidden').val("+" + code + phone);
        });
        $('#company_type').change(function (){
        if ($(this).val() == 4) {
            $('#field-other').show();
            
        } else {
            $('#field-other').hide();
            $('#organization_name').val('');
        }
    });
});
});
</script>